# Mémoire allouée à Gradle (nécessaire pour la décompilation de Minecraft)
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environnement
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

forge_version=52.1.0
forge_version_range=[0,)
loader_version_range=[0,)

mapping_channel=parchment
mapping_version=2024.11.17-1.21.1

## Mod
mod_id=communitytest
mod_name=CommunityTest
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.communityserver.communitytest
mod_authors=CommunityTest Team
mod_description=Mod de démonstration du serveur communautaire : proposition, test et vote des mods.
